### ISSUE TITLE
VoIP calls over facebook messenger is having audio issues

### ISSUE THREAD

**Issue by pragun16** [Evolution-X-Devices/device_xiaomi_violet#2]
If I make a VoIP call over facebook messenger and sometimes in viber, the person at the other end does not hear me although I can hear them. I have tried using multiple headphones/earphones and it did not help. Cellular calls work fine though. Is this a known bug? Can anyone from the community verify this please?

Thanks!

**Comment by bluejeans117** [comment]
Hi, sorry I haven't had the chance to check out this issue. As far as I know, no one has complained of the same in the telegram group. Can you confirm that you've flashed the latest china weekly firmware?
